# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: approval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'approval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pproval.proto\x12\x08\x61pproval\"8\n\x04Step\x12\x0c\n\x04step\x18\x01 \x01(\x05\x12\x12\n\napproverId\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\"x\n\x0f\x41pprovalRequest\x12\x11\n\trequestId\x18\x01 \x01(\x05\x12\x13\n\x0brequesterId\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x1d\n\x05steps\x18\x05 \x03(\x0b\x32\x0e.approval.Step\"\"\n\x10\x41pprovalResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\\\n\x15\x41pprovalResultRequest\x12\x11\n\trequestId\x18\x01 \x01(\x05\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x12\n\napproverId\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\"(\n\x16\x41pprovalResultResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xaf\x01\n\x08\x41pproval\x12H\n\x0fRequestApproval\x12\x19.approval.ApprovalRequest\x1a\x1a.approval.ApprovalResponse\x12Y\n\x14ReturnApprovalResult\x12\x1f.approval.ApprovalResultRequest\x1a .approval.ApprovalResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'approval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEP']._serialized_start=28
  _globals['_STEP']._serialized_end=84
  _globals['_APPROVALREQUEST']._serialized_start=86
  _globals['_APPROVALREQUEST']._serialized_end=206
  _globals['_APPROVALRESPONSE']._serialized_start=208
  _globals['_APPROVALRESPONSE']._serialized_end=242
  _globals['_APPROVALRESULTREQUEST']._serialized_start=244
  _globals['_APPROVALRESULTREQUEST']._serialized_end=336
  _globals['_APPROVALRESULTRESPONSE']._serialized_start=338
  _globals['_APPROVALRESULTRESPONSE']._serialized_end=378
  _globals['_APPROVAL']._serialized_start=381
  _globals['_APPROVAL']._serialized_end=556
# @@protoc_insertion_point(module_scope)
