# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import approval_pb2 as approval__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in approval_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApprovalStub(object):
    """Approval Processing Service와 통신하는 서비스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestApproval = channel.unary_unary(
                '/approval.Approval/RequestApproval',
                request_serializer=approval__pb2.ApprovalRequest.SerializeToString,
                response_deserializer=approval__pb2.ApprovalResponse.FromString,
                _registered_method=True)
        self.ReturnApprovalResult = channel.unary_unary(
                '/approval.Approval/ReturnApprovalResult',
                request_serializer=approval__pb2.ApprovalResultRequest.SerializeToString,
                response_deserializer=approval__pb2.ApprovalResultResponse.FromString,
                _registered_method=True)


class ApprovalServicer(object):
    """Approval Processing Service와 통신하는 서비스 정의
    """

    def RequestApproval(self, request, context):
        """1. [Request Service -> Processing Service] 결재 요청 전달
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnApprovalResult(self, request, context):
        """2. [Processing Service -> Request Service] 결재 결과(승인/반려) 반환
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApprovalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestApproval,
                    request_deserializer=approval__pb2.ApprovalRequest.FromString,
                    response_serializer=approval__pb2.ApprovalResponse.SerializeToString,
            ),
            'ReturnApprovalResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnApprovalResult,
                    request_deserializer=approval__pb2.ApprovalResultRequest.FromString,
                    response_serializer=approval__pb2.ApprovalResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'approval.Approval', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('approval.Approval', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Approval(object):
    """Approval Processing Service와 통신하는 서비스 정의
    """

    @staticmethod
    def RequestApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/approval.Approval/RequestApproval',
            approval__pb2.ApprovalRequest.SerializeToString,
            approval__pb2.ApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnApprovalResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/approval.Approval/ReturnApprovalResult',
            approval__pb2.ApprovalResultRequest.SerializeToString,
            approval__pb2.ApprovalResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
